---
- hosts: ro-consumer
  become: true

  pre_tasks:
  - name: Set hosts file
    copy: src=hosts dest=/etc/hosts owner=root group=root

  roles:
    -
      role: 389ds-server
      dirsrv_suffix: "dc=example,dc=local"
      dirsrv_rootdn_password: consumer
      dirsrv_tls_enabled: true
      dirsrv_tls_cert_file: "ca/ldap-ro-consumer_example_local_cert.pem"
      dirsrv_tls_key_file: "ca/ldap-ro-consumer_example_local.key"
      dirsrv_tls_files_remote: false
      dirsrv_tls_certificate_trusted: false
      dirsrv_tls_enforced: true
      dirsrv_password_storage_scheme: "PBKDF2_SHA256"
      dirsrv_plugins_enabled:
        MemberOf Plugin: true
    -
      role: 389ds-replication
      dirsrv_replica_role: 'consumer'
      dirsrv_suffix: "dc=example,dc=local"
      dirsrv_uri: "ldap://localhost"
      dirsrv_rootdn_password: consumer
      dirsrv_use_starttls: true
      dirsrv_tls_certificate_public_trusted: false
      dirsrv_replication_user_password: "aiGhauD4angai2aif3"
      dirsrv_consumer_referral_to_supplier: "ldap://ldap-ro-supplier.example.local:389/"

