---
- hosts: all
  become: true
  roles:
    -
      role: 389ds-server
      dirsrv_suffix: "dc=example,dc=local"
      dirsrv_rootdn_password: secret
      dirsrv_tls_enabled: true
      dirsrv_tls_cert_file: "ca/ldaptest_example_local_cert.pem"
      dirsrv_tls_key_file: "ca/ldaptest_example_local.key"
      dirsrv_tls_files_remote: false
      dirsrv_tls_certificate_trusted: false
      dirsrv_tls_enforced: true
      dirsrv_password_storage_scheme: "PBKDF2_SHA256"
      dirsrv_plugins_enabled:
        MemberOf Plugin: true
